### PR TITLE
Fix MCContext constructor after LLVM API change

### PR DESCRIPTION
**Pull request by SuitablyMysterious**
From what I understand, prior to this change `MCContext` was implemended as such in a couple of files:

```c++
disassembler->ctx_ = std::make_unique<llvm::MCContext>(
      triple, *disassembler->asm_info_, *disassembler->mri_,
      *disassembler->sti_);
```
This threw the following error: 
```/usr/include/c++/16.1.1/bits/unique_ptr.h:1086:30: error: no matching function for call to ‘llvm::MCContext::MCContext(llvm::Triple&, const llvm::MCAsmInfo&, const llvm::MCRegisterInfo&, const llvm::MCSubtargetInfo&)’```.

This *seems* to have broken; caused by a change to the LLVM internal API.

Note, this might break compatibility with older LLVM/Clang versions; testing in progress.

Also, this is my first PR to a large repo, so feedback is welcome (im only 14, sorry)

### CODE REVIEW

**Comment by SuitablyMysterious** [comment]
I've tested this in a vm with LLVM/Clang 19, 20, 21 and 22 - they all compile; marking as ready to review.

**Comment by dhoekwater** [comment]
Hi @SuitablyMysterious, thanks for your contribution! 14 is an impressive age to start your open source career (I was more concerned with finding ways to to run Minecraft on my school computer at your age). I see that you've signed the Google contributor agreement, but since you mentioned you're under 18, please make sure that a parent or legal guardian signed on your behalf at https://cla.developers.google.com/.

As for this patch, the failure was introduced in https://github.com/google/llvm-propeller/commit/e2c70493656202fc6ac3cdc2b614a15f35928940 (which updated callees of the `MCContext` constructor but didn't actually bump the LLVM hash) and resolved in https://github.com/google/llvm-propeller/commit/ca1556eea46770c57d9866e14e39370c0e664c2d (which actually bumped the pinned LLVM hash). The [CI checks are passing at HEAD](https://github.com/google/llvm-propeller/actions/runs/30297888647/job/90083312869), so I'm closing out this PR as obsolete.
